[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.32"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "3.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/otiai10/copy"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[prune]
  go-tests = true
  unused-packages = true
